steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'decrypt npmrc'
    args:
    - kms
    - decrypt
    - --ciphertext-file=npmrc.enc
    - --plaintext-file=/root/.npmrc
    - --location=global
    - --keyring=my-keyring
    - --key=npm-key
    volumes:
      - name: 'home'
        path: /root/
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install'
    args: ['install']
    env:
    - HOME=/root/
    volumes:
    - name: 'home'
      path: /root/
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/estimate-api-production:${SHORT_SHA}',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/estimate-api-production']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'estimate-api-production',
        '--image',
        'gcr.io/$PROJECT_ID/estimate-api-production:${SHORT_SHA}',
        '--region',
        'us-east1',
        '--platform',
        'managed',
      ]
images:
  - 'gcr.io/$PROJECT_ID/estimate-api-production'


